### ISSUE TITLE
Help always printed when using jira transition in version 1.0.14 darwin

### ISSUE THREAD

**Issue by predatorian3** [Netflix-Skunkworks/go-jira#143]
I haven't had any chance to test this on other machines, but when using the command

```
jira transition "In Process" JIRAQUEUE-1234
```

I get an error and the help is printed for this command. 

```
$ jira transition --verbose "In Process" JIRAQUEUE-1234
usage: jira transition [<flags>] <TRANSITION> <ISSUE>
alias: jira trans [<flags>] <TRANSITION> <ISSUE>

Transition issue to given state

Global flags:
      --help                   Show context-sensitive help (also try --help-long and --help-man).
  -v, --verbose ...            Increase verbosity for debugging
  -e, --endpoint=ENDPOINT      Base URI to use for Jira
  -k, --insecure               Disable TLS certificate verification
  -Q, --quiet                  Suppress output to console
      --unixproxy=UNIXPROXY    Path for a unix-socket proxy
      --socksproxy=SOCKSPROXY  Address for a socks proxy
  -u, --user=USER              Login name used for authentication with Jira service

Optional flags:
  -b, --browse                 Open issue(s) in browser after operation
  -t, --template=TEMPLATE      Template to use for output
      --noedit                 Disable opening the editor
  -m, --comment=COMMENT        Comment message for issue
  -o, --override=OVERRIDE ...  Set issue property
      --resolution=RESOLUTION  Set resolution on transition

Args:
  <TRANSITION>  State to transition issue to
  <ISSUE>       issue to transition

ERROR Invalid Usage: JIRAQUEUE-1234
```

**Comment by coryb** [comment]
Hey, I think this issue was fixed in 1.0.13.  1.0.14 is the [latest release](https://github.com/Netflix-Skunkworks/go-jira/releases/latest)

**Comment by coryb** [comment]
Btw, I noticed you said you were already using 1.0.14, so I am unsure.  It works for me with 1.0.14.  and I re-downloaded the binary from the release page and it also worked.  So the issue might be with your local build if you are using a local build?

**Comment by predatorian3** [comment]
I re-downloaded the pre-compiled binary you provided and I still get the same error.

**Comment by coryb** [comment]
I am super confused then.  It is working for me:
```
~/Downloads/jira-darwin-10.6-amd64 transition --verbose "in process" DEFAULT-2
ERROR Invalid Transition "in process" from "Open", Available: Start Progress, Resolve Issue, Close Issue
```
```
~/Downloads/jira-darwin-10.6-amd64 transition --verbose "Close Issue" DEFAULT-2 --noedit
OK DEFAULT-2 https://go-jira.atlassian.net/browse/DEFAULT-2
```

**Comment by predatorian3** [comment]
Could our Jira instance/project might not have that status, and is kicking back an unknown error to the application?

**Comment by coryb** [comment]
The code should handle that, from my previous runs above I first tried with "in process" which is an invalid transition for this issue and it throws an error message.  If the issue did not exist you would see something like:
```
~/Downloads/jira-darwin-10.6-amd64 transition --verbose "Close Issue" FOOBAR-2
ERROR Issue does not exist or you do not have permission to see it.
```

**Comment by predatorian3** [comment]
Hello. I'm back. I think it is something to do with our Jira instance or something. 

```
pd028300@M1711732 [09:03:15] ~
$ jira version
1.0.20
pd028300@M1711732 [09:03:45] ~
$ jira transitions ETSTOOLS-11052
81: In Process
101: Blocked
141: On Hold
21: Close Issue
pd028300@M1711732 [09:03:55] ~
$ jira transition "In Process" ETSTOOLS-11052
usage: jira transition [<flags>] <TRANSITION> <ISSUE>
alias: jira trans [<flags>] <TRANSITION> <ISSUE>

Transition issue to given state

Global flags:
      --help                   Show context-sensitive help (also try --help-long and --help-man).
  -v, --verbose ...            Increase verbosity for debugging
  -e, --endpoint=ENDPOINT      Base URI to use for Jira
  -k, --insecure               Disable TLS certificate verification
  -Q, --quiet                  Suppress output to console
      --unixproxy=UNIXPROXY    Path for a unix-socket proxy
      --socksproxy=SOCKSPROXY  Address for a socks proxy
  -u, --user=USER              user name used within the Jira service
      --login=LOGIN            login name that corresponds to the user used for authentication

Optional flags:
  -b, --browse                 Open issue(s) in browser after operation
  -t, --template=TEMPLATE      Template to use for output
      --noedit                 Disable opening the editor
  -m, --comment=COMMENT        Comment message for issue
  -o, --override=OVERRIDE ...  Set issue property
      --resolution=RESOLUTION  Set resolution on transition

Args:
  <TRANSITION>  State to transition issue to
  <ISSUE>       issue to transition

ERROR Invalid Usage: unexpected ETSTOOLS-11052
```

**Comment by coryb** [comment]
This is very confusing for me, it looks like your shell is not handling the quoting correctly.  Are you using bash?  It appears that the tool is seeing `jira transition in process ISSUE` and it only wants 2 arguments, so the 3rd is unexpected.  This would imply that your shell is sending `in process` as 2 separate arguments, not sure how that is possible.

**Comment by predatorian3** [comment]
i'm on a Mac, using iTerm2. I should be using Bash, but it may not be doing something correctly like you're saying. Any suggestions on iTerm2 settings?

**Comment by coryb** [comment]
I use mac with iterm2 and bash, so that is not it.  Do you have an alias or function called `jira`?   Or maybe a wrapper shell script?
What does this report:
```
file $(which jira)
type jira
declare -f jira
```

**Comment by predatorian3** [comment]
I do, I call it in a shell script that I put in my path. 

```bash
/usr/local/bin/jira
```

Then the contents of that are:

```bash
/usr/local/bin/jira-darwin-10.6-amd64 --insecure $*
```

I have to include the `--insecure` because our Jira instance isn't setup correctly.

**Comment by coryb** [comment]
Ah, that makes sense, your wrapper script is incorrect, you need to quote the last arg, try something like:
```
/Users/pd028300/Documents/development/go/bin//jira-darwin-10.6-amd64 --insecure "$@"
```

**Comment by predatorian3** [comment]
That seems to have done it! 

```
pd028300@M1711732 [15:13:32] ~/Documents/GenesysCoreSystem
$ jira transition "In Process" ETSTOOLS-9976
? No changes detected, submit anyway? Yes
OK ETSTOOLS-9976 https://jira3.cerner.com/browse/ETSTOOLS-9976
```

Thank you @coryb .
